//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace icportfolio
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ICPORTFOLIOEntities2 : DbContext
    {
        public ICPORTFOLIOEntities2()
            : base("name=ICPORTFOLIOEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<ProjectFeature> ProjectFeatures { get; set; }
        public virtual DbSet<ProjectVideo> ProjectVideos { get; set; }
        public virtual DbSet<Property> Properties { get; set; }
        public virtual DbSet<Type> Types { get; set; }
    }
}
