//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace icportfolio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int ImageiD { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string url { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public bool isMain { get; set; }
        public bool isCode { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
