//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace icportfolio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.Images = new HashSet<Image>();
            this.ProjectFeatures = new HashSet<ProjectFeature>();
            this.ProjectVideos = new HashSet<ProjectVideo>();
        }
    
        public int ProjectID { get; set; }
        public string name { get; set; }
        public Nullable<int> TypeID { get; set; }
        public string summary { get; set; }
        public bool OOP { get; set; }
        public bool Bootstrap { get; set; }
        public bool MVC { get; set; }
        public bool ASP_NET { get; set; }
        public bool SQL { get; set; }
        public bool JSON { get; set; }
        public bool AJAX { get; set; }
        public bool JavaScript { get; set; }
        public string URL { get; set; }
        public string primary_image_URL { get; set; }
        public bool DB_First { get; set; }
        public bool Code_First { get; set; }
        public string Long_Descriptoin { get; set; }
        public string CodeSample1URL { get; set; }
        public string CodeSample2URL { get; set; }
        public string CodeSample3URL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Image> Images { get; set; }
        public virtual Type Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectFeature> ProjectFeatures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectVideo> ProjectVideos { get; set; }
    }
}
