//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace icportfolio
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectFeature
    {
        public int ProjectFeatureID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> PropertyID { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual Property Property { get; set; }
    }
}
